# For *-apache base image
# web:
#     build: ./
#     ports:
#         - "8081:80"
#     expose:
#         - "80"
#     volumes:
#         - ./:/var/www/html/
#     links:
#         - db
#     environment:
#         ENABLE_ENV_FILE: 1
#         ENABLE_LOCALCONF: 1
#         API_TOKEN: "c9575fee817180194a64253fd63cd4dddd0f8220"

    # Uncomment to autostart at boottime
    #restart: always

    # Uncomment to send log output to syslog
    #log_driver: "syslog"
    #log_opt:
    #    tag: "docker-web"

# for *-php-fpm and *-hhvm base image
app:
   build: ./
   expose:
       - "9000"
   volumes:
       - ./:/var/www/html/
   links:
       - db
   environment:
       ENABLE_ENV_FILE: 1
       ENABLE_LOCALCONF: 1
       API_TOKEN: "c9575fee817180194a64253fd63cd4dddd0f8220"

nginx:
   build: ./nginx
   ports:
       - "8081:80"
   links:
       - app
   volumes_from:
       - app

db:
    image: mysql:5.6
    ports:
        - "3307:3306"
    expose:
        - "3307"
    environment:
        MYSQL_ROOT_PASSWORD: secret-root
        MYSQL_DATABASE: web
        MYSQL_USER: web
        MYSQL_PASSWORD: web

    # Uncomment to autostart at boottime
    #restart: always


